((signature (cons a d) (returns pair)) (fragment "cons") (source (srfi 1)))
((signature (list object ...) (returns list)) (fragment "list") (source (srfi 1)))
((signature (xcons d a) (returns pair)) (fragment "xcons") (source (srfi 1)))
((signature (cons* elt1 elt2 ...) (returns object)) (fragment "cons*") (source (srfi 1)))
((signature (make-list n) (returns list)) (signature (make-list n fill) (returns list)) (fragment "make-list") (source (srfi 1)))
((signature (list-tabulate n init-proc) (returns list)) (fragment "list-tabulate") (source (srfi 1)))
((signature (list-copy flist) (returns flist)) (fragment "list-copy") (source (srfi 1)))
((signature (circular-list elt1 elt2 ...) (returns list)) (fragment "circular-list") (source (srfi 1)))
((signature (iota count) (returns list)) (signature (iota count start) (returns list)) (signature (iota count start step) (returns list)) (fragment "iota") (source (srfi 1)))
((signature (circular-list? x) (returns boolean)) (fragment "circular-list-p") (source (srfi 1)))
((signature (dotted-list? x) (returns boolean)) (fragment "dotted-list-p") (source (srfi 1)))
((signature (pair? object) (returns boolean)) (fragment "pair-p") (source (srfi 1)))
((signature (null? object) (returns boolean)) (fragment "null-p") (source (srfi 1)))
((signature (null-list? list) (returns boolean)) (fragment "null-list-p") (source (srfi 1)))
((signature (not-pair? x) (returns boolean)) (fragment "not-pair-p") (source (srfi 1)))
((signature (list= elt= list1 ...) (returns boolean)) (fragment "list=") (source (srfi 1)))
((signature (car pair) (returns value)) (fragment "cdr") (source (srfi 1)))
((signature (cdr pair) (returns value)) (fragment "cdr") (source (srfi 1)))
((signature (caar pair) (returns value)) (fragment "cddddr") (source (srfi 1)))
((signature (cadr pair) (returns value)) (fragment "cddddr") (source (srfi 1)))
((signature (cadr pair) (returns value)) (fragment "cddddr") (source (srfi 1)))
((signature (cddr pair) (returns value)) (fragment "cddddr") (source (srfi 1)))
((signature (caaar pair) (returns value)) (fragment "cddddr") (source (srfi 1)))
((signature (caadr pair) (returns value)) (fragment "cddddr") (source (srfi 1)))
((signature (cadar pair) (returns value)) (fragment "cddddr") (source (srfi 1)))
((signature (caddr pair) (returns value)) (fragment "cddddr") (source (srfi 1)))
((signature (cdaar pair) (returns value)) (fragment "cddddr") (source (srfi 1)))
((signature (cdadr pair) (returns value)) (fragment "cddddr") (source (srfi 1)))
((signature (cddar pair) (returns value)) (fragment "cddddr") (source (srfi 1)))
((signature (cdddr pair) (returns value)) (fragment "cddddr") (source (srfi 1)))
((signature (caaaar pair) (returns value)) (fragment "cddddr") (source (srfi 1)))
((signature (caaadr pair) (returns value)) (fragment "cddddr") (source (srfi 1)))
((signature (caadar pair) (returns value)) (fragment "cddddr") (source (srfi 1)))
((signature (caaddr pair) (returns value)) (fragment "cddddr") (source (srfi 1)))
((signature (cadaar pair) (returns value)) (fragment "cddddr") (source (srfi 1)))
((signature (cadadr pair) (returns value)) (fragment "cddddr") (source (srfi 1)))
((signature (caddar pair) (returns value)) (fragment "cddddr") (source (srfi 1)))
((signature (cadddr pair) (returns value)) (fragment "cddddr") (source (srfi 1)))
((signature (cdaaar pair) (returns value)) (fragment "cddddr") (source (srfi 1)))
((signature (cdaadr pair) (returns value)) (fragment "cddddr") (source (srfi 1)))
((signature (cdadar pair) (returns value)) (fragment "cddddr") (source (srfi 1)))
((signature (cdaddr pair) (returns value)) (fragment "cddddr") (source (srfi 1)))
((signature (cddaar pair) (returns value)) (fragment "cddddr") (source (srfi 1)))
((signature (cddadr pair) (returns value)) (fragment "cddddr") (source (srfi 1)))
((signature (cdddar pair) (returns value)) (fragment "cddddr") (source (srfi 1)))
((signature (cddddr pair) (returns value)) (fragment "cddddr") (source (srfi 1)))
((signature (list-ref clist i) (returns value)) (fragment "list-ref") (source (srfi 1)))
((signature (first pair) (returns object)) (fragment "first") (source (srfi 1)))
((signature (third pair) (returns object)) (fragment "third") (source (srfi 1)))
((signature (fourth pair) (returns object)) (fragment "fourth") (source (srfi 1)))
((signature (fifth pair) (returns object)) (fragment "fifth") (source (srfi 1)))
((signature (sixth pair) (returns object)) (fragment "sixth") (source (srfi 1)))
((signature (seventh pair) (returns object)) (fragment "seventh") (source (srfi 1)))
((signature (eighth pair) (returns object)) (fragment "eighth") (source (srfi 1)))
((signature (ninth pair) (returns object)) (fragment "ninth") (source (srfi 1)))
((signature (tenth pair) (returns object)) (fragment "tenth") (source (srfi 1)))
((signature (car+cdr pair) (returns x y)) (fragment "car+cdr") (source (srfi 1)))
((signature (drop x i) (returns object)) (fragment "drop") (source (srfi 1)))
((signature (take-right flist i) (returns object)) (fragment "take-right") (source (srfi 1)))
((signature (drop-right flist i) (returns list)) (fragment "drop-right") (source (srfi 1)))
((signature (take! x i) (returns list)) (fragment "take!") (source (srfi 1)))
((signature (drop-right! flist i) (returns list)) (fragment "drop-right!") (source (srfi 1)))
((signature (split-at x i) (returns list object)) (fragment "split-at") (source (srfi 1)))
((signature (split-at! x i) (returns list object)) (fragment "split-at!") (source (srfi 1)))
((signature (last pair) (returns object)) (fragment "last") (source (srfi 1)))
((signature (last-pair pair) (returns pair)) (fragment "last-pair") (source (srfi 1)))
((signature (length list) (returns integer)) (fragment "length") (source (srfi 1)))
((signature (length+ clist) (returns (or integer #f))) (fragment "length+") (source (srfi 1)))
((signature (append list1 ...) (returns list)) (fragment "append") (source (srfi 1)))
((signature (append! list1 ...) (returns list)) (fragment "append!") (source (srfi 1)))
((signature (concatenate list-of-lists) (returns value)) (fragment "concatenate") (source (srfi 1)))
((signature (concatenate! list-of-lists) (returns value)) (fragment "concatenate!") (source (srfi 1)))
((signature (reverse list) (returns list)) (fragment "reverse") (source (srfi 1)))
((signature (reverse! list) (returns list)) (fragment "reverse!") (source (srfi 1)))
((signature (append-reverse rev-head tail) (returns list)) (fragment "append-reverse") (source (srfi 1)))
((signature (append-reverse! rev-head tail) (returns list)) (fragment "append-reverse") (source (srfi 1)))
((signature (zip clist1 clist2 ...) (returns list)) (fragment "zip") (source (srfi 1)))
((signature (unzip1 list) (returns list)) (fragment "unzip1") (source (srfi 1)))
((signature (unzip3 list) (returns list list list)) (fragment "unzip3") (source (srfi 1)))
((signature (unzip5 list) (returns list list list list list)) (fragment "unzip5") (source (srfi 1)))
((signature (count pred clist1 clist2) (returns integer)) (fragment "count") (source (srfi 1)))
((signature (fold kons knil clist1 clist2 ...) (returns value)) (fragment "fold") (source (srfi 1)))
((signature (fold-right kons knil clist1 clist2 ...) (returns value)) (fragment "fold-right") (source (srfi 1)))
((signature (pair-fold kons knil clist1 clist2 ...) (returns value)) (fragment "pair-fold") (source (srfi 1)))
((signature (pair-fold-right kons knil clist1 clist2 ...) (returns value)) (fragment "pair-fold-right") (source (srfi 1)))
((signature (reduce f ridentity list) (returns value)) (fragment "reduce") (source (srfi 1)))
((signature (reduce-right f ridentity list) (returns value)) (fragment "reduce-right") (source (srfi 1)))
((signature (unfold p f g seed) (returns list)) (signature (unfold p f g seed tail-gen) (returns list)) (fragment "unfold") (source (srfi 1)))
((signature (unfold-right p f g seed) (returns list)) (signature (unfold-right p f g seed tail) (returns list)) (fragment "unfold-right") (source (srfi 1)))
((signature (map proc clist1 clist2 ...) (returns list)) (fragment "map") (source (srfi 1)))
((signature (for-each proc clist1 clist2 ...) (returns unspecified)) (fragment "for-each") (source (srfi 1)))
((signature (append-map f clist1 clist2 ...) (returns value)) (fragment "append-map") (source (srfi 1)))
((signature (append-map! f clist1 clist2 ...) (returns value)) (fragment "append-map") (source (srfi 1)))
((signature (map! f list1 clist2 ...) (returns list)) (fragment "map!") (source (srfi 1)))
((signature (map-in-order f clist1 clist2 ...) (returns list)) (fragment "map-in-order") (source (srfi 1)))
((signature (pair-for-each f clist1 clist2 ...) (returns unspecific)) (fragment "pair-for-each") (source (srfi 1)))
((signature (filter-map f clist1 clist2 ...) (returns list)) (fragment "filter-map") (source (srfi 1)))
((signature (filter pred list) (returns list)) (fragment "filter") (source (srfi 1)))
((signature (partition pred list) (returns list list)) (fragment "partition") (source (srfi 1)))
((signature (remove pred list) (returns list)) (fragment "remove") (source (srfi 1)))
((signature (filter! pred list) (returns list)) (fragment "filter!") (source (srfi 1)))
((signature (partition! pred list) (returns list list)) (fragment "partition!") (source (srfi 1)))
((signature (remove! pred list) (returns list)) (fragment "remove!") (source (srfi 1)))
((signature (find pred clist) (returns value)) (fragment "find") (source (srfi 1)))
((signature (find-tail pred clist) (returns (or pair #f))) (fragment "find-tail") (source (srfi 1)))
((signature (take-while pred clist) (returns list)) (fragment "take-while") (source (srfi 1)))
((signature (take-while! pred clist) (returns list)) (fragment "take-while") (source (srfi 1)))
((signature (drop-while pred clist) (returns list)) (fragment "drop-while") (source (srfi 1)))
((signature (span pred clist) (returns list clist)) (fragment "span") (source (srfi 1)))
((signature (span! pred list) (returns list list)) (fragment "span!") (source (srfi 1)))
((signature (break pred clist) (returns list clist)) (fragment "break") (source (srfi 1)))
((signature (break! pred list) (returns list list)) (fragment "break!") (source (srfi 1)))
((signature (any pred clist1 clist2 ...) (returns value)) (fragment "any") (source (srfi 1)))
((signature (every pred clist1 clist2 ...) (returns value)) (fragment "every") (source (srfi 1)))
((signature (list-index pred clist1 clist2 ...) (returns (or integer #f))) (fragment "list-index") (source (srfi 1)))
((signature (member x list) (returns list)) (signature (member x list =) (returns list)) (fragment "member") (source (srfi 1)))
((signature (memq x list) (returns list)) (fragment "memq") (source (srfi 1)))
((signature (memv x list) (returns list)) (fragment "memv") (source (srfi 1)))
((signature (delete x list) (returns list)) (signature (delete x list =) (returns list)) (fragment "delete") (source (srfi 1)))
((signature (delete! x list) (returns list)) (signature (delete! x list =) (returns list)) (fragment "delete!") (source (srfi 1)))
((signature (delete-duplicates list) (returns list)) (signature (delete-duplicates list =) (returns list)) (fragment "delete-duplicates") (source (srfi 1)))
((signature (delete-duplicates! list) (returns list)) (signature (delete-duplicates! list =) (returns list)) (fragment "delete-duplicates") (source (srfi 1)))
((signature (assoc key alist) (returns (or pair #f))) (signature (assoc key alist =) (returns (or pair #f))) (fragment "assoc") (source (srfi 1)))
((signature (assq key alist) (returns (or pair #f))) (fragment "assq") (source (srfi 1)))
((signature (assv key alist) (returns (or pair #f))) (fragment "assv") (source (srfi 1)))
((signature (alist-cons key datum alist) (returns alist)) (fragment "alist-cons") (source (srfi 1)))
((signature (alist-copy alist) (returns alist)) (fragment "alist-copy") (source (srfi 1)))
((signature (alist-delete key alist) (returns alist)) (signature (alist-delete key alist =) (returns alist)) (fragment "alist-delete") (source (srfi 1)))
((signature (alist-delete! key alist) (returns alist)) (signature (alist-delete! key alist =) (returns alist)) (fragment "alist-delete") (source (srfi 1)))
((signature (lset<= = list1 ...) (returns boolean)) (fragment "lset<=") (source (srfi 1)))
((signature (lset= = list1 list2 ...) (returns boolean)) (fragment "lset=") (source (srfi 1)))
((signature (lset-adjoin = list elt1 ...) (returns list)) (fragment "lset-adjoin") (source (srfi 1)))
((signature (lset-union = list1 ...) (returns list)) (fragment "lset-union") (source (srfi 1)))
((signature (lset-intersection = list1 list2 ...) (returns list)) (fragment "lset-intersection") (source (srfi 1)))
((signature (lset-difference = list1 list2 ...) (returns list)) (fragment "lset-difference") (source (srfi 1)))
((signature (lset-xor = list1 ...) (returns list)) (fragment "lset-xor") (source (srfi 1)))
((signature (lset-diff+intersection = list1 list2 ...) (returns list list)) (fragment "lset-diff+intersection") (source (srfi 1)))
((signature (lset-union! = list1 ...) (returns list)) (fragment "lset-union") (source (srfi 1)))
((signature (lset-intersection! = list1 list2 ...) (returns list)) (fragment "lset-intersection") (source (srfi 1)))
((signature (lset-difference! = list1 list2 ...) (returns list)) (fragment "lset-difference") (source (srfi 1)))
((signature (lset-xor! = list1 ...) (returns list)) (fragment "lset-xor") (source (srfi 1)))
((signature (lset-diff+intersection! = list1 list2 ...) (returns list list)) (fragment "lset-diff+intersection") (source (srfi 1)))
((signature (set-car! pair object) (returns unspecified)) (fragment "set-car") (source (srfi 1)))
((signature (set-cdr! pair object) (returns unspecified)) (fragment "set-cdr") (source (srfi 1)))