(define-library (srfi-tools chart)
  (export srfi-generate-chart)
  (import (scheme base)
	  (scheme file)
	  (scheme write)
	  (srfi 1)
	  (srfi 19)
	  (srfi 130)
	  (srfi-tools data)
	  (srfi-tools path)
	  (srfi-tools private command)
	  (srfi-tools private os)
	  (srfi-tools private path)
	  (srfi-tools private port)
	  (srfi-tools private time))
  (include "chart.scm"))