#+Title: SRFI tools

This directory contains tools to help people read and write SRFIs.

The tools can be accessed in two ways:

1. By importing the libraries into a Scheme implementation.

2. By using the ~srfi~ command line tool from an OS shell.

The tools are written in portable R7RS Scheme, except for a few
implementation-dependent procedures which are gathered in the ~sysdep~
library.

The ~private~ directory contains utility code which does not deal with
SRFI specifically.

Like SRFIs themselves, the tools are released under the MIT License.

* Command line

The command line ~srfi~ command. Each tool is a subcommand.

When no subcommand is given, the default command is run.

When a SRFI number is given in lieu of a subcommand, the default SRFI
command is run.

If you're using ~bash~ (or maybe ~zsh~), execute ~eval "$(srfi
complete bash)"~ to enable tab completion for the subcommands.

* Installation

The ~srfi~ command works with Chibi Scheme, Chicken Scheme, and
Gauche.

For Chibi or Gauche, just make a symbolic link from the corresponding
script in ~srfi-tools/wrapper/~ to ~srfi~ somewhere on your ~$PATH~.

For Chicken, there is a ~srfi-tools.egg~ file.

If you don't keep your SRFI repo clones under ~~/srfi/~, you can set
~SRFI_HOME~ to the root of those clones.  You should at least have a
clone of ~srfi-common/~ there.