((number 0)
 (status final)
 (title "Feature-based conditional expansion construct")
 (authors "Marc Feeley")
 (see-also)
 (keywords "features")
 (draft-date "1999/01/05")
 (done-date "1999/5/7"))
((number 1)
 (status final)
 (title "List Library")
 (authors "Olin Shivers")
 (see-also)
 (keywords "data-structure")
 (draft-date "1998/12/22")
 (done-date "1999/10/9"))
((number 2)
 (status final)
 (title "AND-LET*: an AND with local bindings, a guarded LET* special form")
 (authors "Oleg Kiselyov")
 (see-also)
 (keywords "binding" "control-flow")
 (draft-date "1998/12/28")
 (done-date "1999/3/1"))
((number 3)
 (status withdrawn)
 (title "List-Set Library")
 (authors "Olin Shivers")
 (see-also)
 (keywords "data-structure")
 (draft-date "1999/1/12")
 (done-date "1999/08/26"))
((number 4)
 (status final)
 (title "Homogeneous numeric vector datatypes")
 (authors "Marc Feeley")
 (see-also 160)
 (keywords "data-structure")
 (draft-date "1999/1/19")
 (done-date "1999/5/22"))
((number 5)
 (status final)
 (title "A compatible let form with signatures and rest arguments")
 (authors "Andy Gaynor")
 (see-also)
 (keywords "binding")
 (draft-date "1999/2/10")
 (done-date "1999/4/26"))
((number 6)
 (status final)
 (title "Basic String Ports")
 (authors "William D Clinger")
 (see-also)
 (keywords "i/o" "operating-system")
 (draft-date "1999/04/26")
 (done-date "1999/7/1"))
((number 7)
 (status final)
 (title "Feature-based program configuration language")
 (authors "Richard Kelsey")
 (see-also)
 (keywords "features")
 (draft-date "1999/05/26")
 (done-date "1999/8/19"))
((number 8)
 (status final)
 (title "receive: Binding to multiple values")
 (authors "John David Stone")
 (see-also)
 (keywords "binding")
 (draft-date "1999/07/01")
 (done-date "1999/8/30"))
((number 9)
 (status final)
 (title "Defining Record Types")
 (authors "Richard Kelsey")
 (see-also)
 (keywords "data-structure")
 (draft-date "1999/07/07")
 (done-date "1999/9/9"))
((number 10)
 (status final)
 (title "#, external form")
 (authors "Oleg Kiselyov")
 (see-also)
 (keywords "reader-syntax")
 (draft-date "1999/09/21")
 (done-date "2000/1/13"))
((number 11)
 (status final)
 (title "Syntax for receiving multiple values")
 (authors "Lars T Hansen")
 (see-also)
 (keywords "binding")
 (draft-date "1999/09/14")
 (done-date "2000/3/15"))
((number 12)
 (status withdrawn)
 (title "Exception Handling")
 (authors "William Clinger, R. Kent Dybvig, Matthew Flatt, and Marc Feeley")
 (see-also)
 (keywords "control-flow" "exceptions")
 (draft-date "1999/10/10")
 (done-date "2000/01/22"))
((number 13)
 (status final)
 (title "String Libraries")
 (authors "Olin Shivers")
 (see-also 130)
 (keywords "data-structure")
 (draft-date "1999/10/18")
 (done-date "2000/12/28"))
((number 14)
 (status final)
 (title "Character-set Library")
 (authors "Olin Shivers")
 (see-also)
 (keywords "data-structure")
 (draft-date "1999/10/30")
 (done-date "2000/12/28"))
((number 15)
 (status withdrawn)
 (title "Syntax for dynamic scoping")
 (authors "Lars T Hansen")
 (see-also)
 (keywords "binding")
 (draft-date "1999/11/06")
 (done-date "2000/03/10"))
((number 16)
 (status final)
 (title "Syntax for procedures of variable arity")
 (authors "Lars T Hansen")
 (see-also)
 (keywords "pattern-matching")
 (draft-date "1999/11/06")
 (done-date "2000/3/10"))
((number 17)
 (status final)
 (title "Generalized set!")
 (authors "Per Bothner")
 (see-also)
 (keywords "assignment")
 (draft-date "2000/01/16")
 (done-date "2000/7/24"))
((number 18)
 (status final)
 (title "Multithreading support")
 (authors "Marc Feeley")
 (see-also)
 (keywords "concurrency")
 (draft-date "2000/02/07")
 (done-date "2001/3/14"))
((number 19)
 (status final)
 (title "Time Data Types and Procedures")
 (authors "Will Fitzgerald")
 (see-also)
 (keywords "data-structure")
 (draft-date "2000/02/28")
 (done-date "2000/8/31"))
((number 20)
 (status withdrawn)
 (title "Simple object system")
 (authors "Christian Queinnec")
 (see-also)
 (keywords "miscellaneous")
 (draft-date "2000/04/16")
 (done-date "2001/04/29"))
((number 21)
 (status final)
 (title "Real-time multithreading support")
 (authors "Marc Feeley")
 (see-also)
 (keywords "concurrency")
 (draft-date "2000/05/12")
 (done-date "2001/3/2"))
((number 22)
 (status final)
 (title "Running Scheme Scripts on Unix")
 (authors "Martin Gasbichler and Michael Sperber")
 (see-also)
 (keywords "operating-system")
 (draft-date "2001/03/08")
 (done-date "2002/1/20"))
((number 23)
 (status final)
 (title "Error reporting mechanism")
 (authors "Stephan Houben")
 (see-also)
 (keywords "control-flow" "error-handling")
 (draft-date "2001/03/09")
 (done-date "2001/6/22"))
((number 24)
 (status withdrawn)
 (title "Define-syntax in local lexical scopes")
 (authors "Antti Huima")
 (see-also)
 (keywords "syntax")
 (draft-date "2001/06/25")
 (done-date "2002/04/12"))
((number 25)
 (status final)
 (title "Multi-dimensional Array Primitives")
 (authors "Jussi Piitulainen")
 (see-also)
 (keywords "data-structure")
 (draft-date "2001/11/12")
 (done-date "2002/5/21"))
((number 26)
 (status final)
 (title "Notation for Specializing Parameters without Currying")
 (authors "Sebastian Egner")
 (see-also 156)
 (keywords "syntax")
 (draft-date "2002/02/06")
 (done-date "2002/2/14"))
((number 27)
 (status final)
 (title "Sources of Random Bits")
 (authors "Sebastian Egner")
 (see-also)
 (keywords "miscellaneous")
 (draft-date "2002/02/12")
 (done-date "2002/6/3"))
((number 28)
 (status final)
 (title "Basic Format Strings ")
 (authors "Scott G. Miller")
 (see-also 48 159)
 (keywords "i/o")
 (draft-date "2002/03/22")
 (done-date "2002/6/25"))
((number 29)
 (status final)
 (title "Localization ")
 (authors "Scott G. Miller")
 (see-also)
 (keywords "i/o")
 (draft-date "2002/03/26")
 (done-date "2002/8/1"))
((number 30)
 (status final)
 (title "Nested Multi-line Comments")
 (authors "Martin Gasbichler")
 (see-also)
 (keywords "reader-syntax")
 (draft-date "2002/04/12")
 (done-date "2002/8/7"))
((number 31)
 (status final)
 (title "A special form `rec' for recursive evaluation")
 (authors "Mirko.Luedde@Computer.Org")
 (see-also)
 (keywords "miscellaneous")
 (draft-date "2002/05/24")
 (done-date "2002/12/2"))
((number 32)
 (status withdrawn)
 (title "Sort Libraries")
 (authors "Olin Shivers")
 (see-also)
 (keywords "algorithm")
 (draft-date "2002/07/15")
 (done-date "2003/07/17"))
((number 33)
 (status withdrawn)
 (title "Integer Bitwise-operation Library")
 (authors "Olin Shivers")
 (see-also)
 (keywords "data-structure")
 (draft-date "2002/07/15")
 (done-date "2003/07/17"))
((number 34)
 (status final)
 (title "Exception Handling for Programs")
 (authors "Richard Kelsey and Michael Sperber")
 (see-also)
 (keywords "exceptions")
 (draft-date "2002/07/23")
 (done-date "2002/12/1"))
((number 35)
 (status final)
 (title "Conditions")
 (authors "Richard Kelsey and Michael Sperber")
 (see-also)
 (keywords "exceptions")
 (draft-date "2002/07/23")
 (done-date "2002/12/1"))
((number 36)
 (status final)
 (title "I/O Conditions")
 (authors "Michael Sperber")
 (see-also)
 (keywords "exceptions" "i/o")
 (draft-date "2002/07/23")
 (done-date "2002/12/1"))
((number 37)
 (status final)
 (title "args-fold: a program argument processor")
 (authors "Anthony Carrico")
 (see-also)
 (keywords "operating-system")
 (draft-date "2002/09/23")
 (done-date "2003/1/13"))
((number 38)
 (status final)
 (title "External Representation for Data With Shared Structure")
 (authors "Ray Dillinger")
 (see-also)
 (keywords "i/o")
 (draft-date "2002/12/16")
 (done-date "2003/4/2"))
((number 39)
 (status final)
 (title "Parameter objects")
 (authors "Marc Feeley")
 (see-also)
 (keywords "binding" "parameters")
 (draft-date "2002/12/21")
 (done-date "2003/6/30"))
((number 40)
 (status withdrawn)
 (title "A Library of Streams")
 (authors "Philip L. Bewig")
 (see-also 41)
 (keywords "data-structure" "superseded")
 (draft-date "2003/02/03")
 (done-date "2017/8/10"))
((number 41)
 (status final)
 (title "Streams")
 (authors "Philip L. Bewig")
 (see-also 40)
 (keywords "data-structure")
 (draft-date "2007/10/21")
 (done-date "2008/1/24"))
((number 42)
 (status final)
 (title "Eager Comprehensions")
 (authors "Sebastian Egner")
 (see-also)
 (keywords "control-flow")
 (draft-date "2003/02/20")
 (done-date "2003/7/7"))
((number 43)
 (status final)
 (title "Vector library")
 (authors "Taylor Campbell")
 (see-also 133)
 (keywords "data-structure")
 (draft-date "2003/04/03")
 (done-date "2004/10/26"))
((number 44)
 (status final)
 (title "Collections")
 (authors "Scott G. Miller")
 (see-also)
 (keywords "data-structure")
 (draft-date "2003/04/28")
 (done-date "2004/3/7"))
((number 45)
 (status final)
 (title "Primitives for Expressing Iterative Lazy Algorithms")
 (authors "André van Tonder")
 (see-also 155)
 (keywords "data-structure")
 (draft-date "2003/09/23")
 (done-date "2004/4/5"))
((number 46)
 (status final)
 (title "Basic Syntax-rules Extensions")
 (authors "Taylor Campbell")
 (see-also)
 (keywords "syntax")
 (draft-date "2003/10/06")
 (done-date "2005/2/28"))
((number 47)
 (status final)
 (title "Array")
 (authors "Aubrey Jaffer")
 (see-also)
 (keywords "data-structure")
 (draft-date "2003/11/11")
 (done-date "2004/6/14"))
((number 48)
 (status final)
 (title "Intermediate Format Strings")
 (authors "Ken Dickey")
 (see-also 28 159)
 (keywords "i/o")
 (draft-date "2003/11/25")
 (done-date "2004/3/2"))
((number 49)
 (status final)
 (title "Indentation-sensitive syntax")
 (authors "Egil Möller")
 (see-also)
 (keywords "reader-syntax")
 (draft-date "2003/11/30")
 (done-date "2005/7/22"))
((number 50)
 (status withdrawn)
 (title "Mixing Scheme and C")
 (authors "Richard Kelsey and Michael Sperber")
 (see-also)
 (keywords "operating-system")
 (draft-date "2003/12/22")
 (done-date "2005/12/20"))
((number 51)
 (status final)
 (title "Handling rest list")
 (authors "Joo ChurlSoo")
 (see-also)
 (keywords "multiple-value-returns")
 (draft-date "2004/01/18")
 (done-date "2004/6/7"))
((number 52)
 (status withdrawn)
 (title "Permitting and Supporting Extended Character Sets")
 (authors "Thomas Lord (lord@emf.net aka lord@gnu.org)")
 (see-also)
 (keywords "data-structure")
 (draft-date "2004/02/09")
 (done-date "2004/06/17"))
((number 53)
 (status withdrawn)
 (title "Syntactic computations with computation-rules")
 (authors "André van Tonder")
 (see-also)
 (keywords "syntax")
 (draft-date "2004/03/16")
 (done-date "2004/09/06"))
((number 54)
 (status final)
 (title "Formatting")
 (authors "Joo ChurlSoo")
 (see-also)
 (keywords "i/o")
 (draft-date "2004/03/22")
 (done-date "2004/6/24"))
((number 55)
 (status final)
 (title "require-extension")
 (authors "Felix L. Winkelmann and D.C. Frost")
 (see-also)
 (keywords "features")
 (draft-date "2004/06/07")
 (done-date "2004/11/5"))
((number 56)
 (status withdrawn)
 (title "Binary I/O")
 (authors "Alex Shinn")
 (see-also)
 (keywords "i/o")
 (draft-date "2004/06/14")
 (done-date "2005/10/31"))
((number 57)
 (status final)
 (title "Records")
 (authors "André van Tonder")
 (see-also)
 (keywords "data-structure")
 (draft-date "2004/09/08")
 (done-date "2005/3/7"))
((number 58)
 (status final)
 (title "Array Notation")
 (authors "Aubrey Jaffer")
 (see-also)
 (keywords "reader-syntax")
 (draft-date "2004/11/26")
 (done-date "2005/3/8"))
((number 59)
 (status final)
 (title "Vicinity")
 (authors "Aubrey Jaffer")
 (see-also)
 (keywords "i/o")
 (draft-date "2004/12/30")
 (done-date "2005/3/8"))
((number 60)
 (status final)
 (title "Integers as Bits")
 (authors "Aubrey Jaffer")
 (see-also)
 (keywords "data-structure")
 (draft-date "2005/01/03")
 (done-date "2005/3/8"))
((number 61)
 (status final)
 (title "A more general cond clause")
 (authors "Taylor Campbell")
 (see-also)
 (keywords "binding" "control-flow")
 (draft-date "2005/01/03")
 (done-date "2005/7/21"))
((number 62)
 (status final)
 (title "S-expression comments")
 (authors "Taylor Campbell")
 (see-also)
 (keywords "reader-syntax")
 (draft-date "2005/01/03")
 (done-date "2005/7/21"))
((number 63)
 (status final)
 (title "Homogeneous and Heterogeneous Arrays")
 (authors "Aubrey Jaffer")
 (see-also)
 (keywords "data-structure")
 (draft-date "2005/01/17")
 (done-date "2005/4/27"))
((number 64)
 (status final)
 (title "A Scheme API for test suites")
 (authors "Per Bothner")
 (see-also)
 (keywords "testing")
 (draft-date "2005/01/28")
 (done-date "2006/6/18"))
((number 65)
 (status withdrawn)
 (title
  "define-immutable: A Syntax to Define Identifiers With Immutable Values")
 (authors "Andrew Wilcox")
 (see-also)
 (keywords "binding" "lazy-evaluation")
 (draft-date "2005/06/19")
 (done-date "2005/05/17"))
((number 66)
 (status final)
 (title "Octet Vectors")
 (authors "Michael Sperber")
 (see-also)
 (keywords "data-structure")
 (draft-date "2005/03/11")
 (done-date "2005/12/15"))
((number 67)
 (status final)
 (title "Compare Procedures")
 (authors "Sebastian Egner and Jens Axel Søgaard")
 (see-also)
 (keywords "comparison")
 (draft-date "2005/04/05")
 (done-date "2005/9/11"))
((number 68)
 (status withdrawn)
 (title "Comprehensive I/O")
 (authors "Michael Sperber")
 (see-also)
 (keywords "i/o")
 (draft-date "2005/04/13")
 (done-date "2005/11/29"))
((number 69)
 (status final)
 (title "Basic hash tables")
 (authors "Panu Kalliokoski")
 (see-also 125 126)
 (keywords "data-structure")
 (draft-date "2005/04/25")
 (done-date "2005/9/14"))
((number 70)
 (status final)
 (title "Numbers")
 (authors "Aubrey Jaffer")
 (see-also)
 (keywords "arithmetic" "data-structure")
 (draft-date "2005/05/15")
 (done-date "2005/9/11"))
((number 71)
 (status final)
 (title "Extended LET-syntax for multiple values")
 (authors "Sebastian Egner")
 (see-also)
 (keywords "binding")
 (draft-date "2005/05/16")
 (done-date "2005/8/12"))
((number 72)
 (status final)
 (title "Hygienic macros")
 (authors "André van Tonder")
 (see-also)
 (keywords "syntax")
 (draft-date "2005/06/14")
 (done-date "2005/9/21"))
((number 73)
 (status withdrawn)
 (title "Exact Infinities")
 (authors "Chongkai Zhu")
 (see-also)
 (keywords "arithmetic")
 (draft-date "2005/06/19")
 (done-date "2005/11/30"))
((number 74)
 (status final)
 (title "Octet-Addressed Binary Blocks")
 (authors "Michael Sperber")
 (see-also)
 (keywords "data-structure")
 (draft-date "2005/07/06")
 (done-date "2005/12/15"))
((number 75)
 (status withdrawn)
 (title "R6RS Unicode data")
 (authors "Matthew Flatt and Marc Feeley")
 (see-also)
 (keywords "internationalization")
 (draft-date "2005/07/12")
 (done-date "2006/05/27"))
((number 76)
 (status withdrawn)
 (title "R6RS Records")
 (authors "Will Clinger, R. Kent Dybvig, Michael Sperber, Anton van Straaten")
 (see-also)
 (keywords "data-structure")
 (draft-date "2005/09/12")
 (done-date "2006/04/24"))
((number 77)
 (status withdrawn)
 (title "Preliminary Proposal for R6RS Arithmetic")
 (authors "William D Clinger and Michael Sperber")
 (see-also)
 (keywords "arithmetic")
 (draft-date "2005/10/06")
 (done-date "2006/09/13"))
((number 78)
 (status final)
 (title "Lightweight testing")
 (authors "Sebastian Egner")
 (see-also)
 (keywords "testing")
 (draft-date "2005/11/11")
 (done-date "2006/3/6"))
((number 79)
 (status withdrawn)
 (title "Primitive I/O")
 (authors "Michael Sperber")
 (see-also)
 (keywords "i/o")
 (draft-date "2005/11/24")
 (done-date "2006/11/16"))
((number 80)
 (status withdrawn)
 (title "Stream I/O")
 (authors "Michael Sperber")
 (see-also)
 (keywords "i/o")
 (draft-date "2005/11/24")
 (done-date "2006/11/20"))
((number 81)
 (status withdrawn)
 (title "Port I/O")
 (authors "Michael Sperber")
 (see-also)
 (keywords "i/o")
 (draft-date "2005/11/24")
 (done-date "2006/11/20"))
((number 82)
 (status withdrawn)
 (title "Stream Ports")
 (authors "Michael Sperber")
 (see-also)
 (keywords "i/o")
 (draft-date "2005/11/24")
 (done-date "2006/11/20"))
((number 83)
 (status withdrawn)
 (title "R6RS Library Syntax")
 (authors "Matthew Flatt and Kent Dybvig")
 (see-also)
 (keywords "modules")
 (draft-date "2005/11/30")
 (done-date "2006/09/13"))
((number 84)
 (status withdrawn)
 (title "Universal Identifiers")
 (authors "Andrew Wilcox")
 (see-also)
 (keywords "data-structure")
 (draft-date "2006/01/26")
 (done-date "2006/11/09"))
((number 85)
 (status withdrawn)
 (title "Recursive Equivalence Predicates")
 (authors "William D Clinger")
 (see-also)
 (keywords "comparison")
 (draft-date "2006/03/09")
 (done-date "2006/10/21"))
((number 86)
 (status final)
 (title
  "MU and NU simulating VALUES & CALL-WITH-VALUES, and their related LET-syntax")
 (authors "Joo ChurlSoo")
 (see-also)
 (keywords "data-structure" "multiple-value-returns")
 (draft-date "2006/04/04")
 (done-date "2006/6/20"))
((number 87)
 (status final)
 (title "=> in case clauses")
 (authors "Chongkai Zhu")
 (see-also)
 (keywords "control-flow")
 (draft-date "2006/04/10")
 (done-date "2006/10/18"))
((number 88)
 (status final)
 (title "Keyword objects")
 (authors "Marc Feeley")
 (see-also)
 (keywords "reader-syntax")
 (draft-date "2006/04/10")
 (done-date "2007/7/3"))
((number 89)
 (status final)
 (title "Optional positional and named parameters")
 (authors "Marc Feeley")
 (see-also)
 (keywords "binding")
 (draft-date "2006/04/10")
 (done-date "2007/7/10"))
((number 90)
 (status final)
 (title "Extensible hash table constructor")
 (authors "Marc Feeley")
 (see-also)
 (keywords "data-structure")
 (draft-date "2006/04/12")
 (done-date "2007/7/10"))
((number 91)
 (status withdrawn)
 (title "Extended ports")
 (authors "Marc Feeley")
 (see-also)
 (keywords "i/o")
 (draft-date "2006/04/12")
 (done-date "2007/07/10"))
((number 92)
 (status withdrawn)
 (title "ALAMBDA and ALAMBDA*")
 (authors "Joo ChurlSoo")
 (see-also)
 (keywords "miscellaneous" "type-checking")
 (draft-date "2006/05/21")
 (done-date "2007/04/09"))
((number 93)
 (status withdrawn)
 (title "R6RS Syntax-Case Macros")
 (authors "Kent Dybvig")
 (see-also)
 (keywords "syntax")
 (draft-date "2006/06/21")
 (done-date "2006/08/23"))
((number 94)
 (status final)
 (title "Type-Restricted Numerical Functions")
 (authors "Aubrey Jaffer")
 (see-also)
 (keywords "arithmetic")
 (draft-date "2006/09/14")
 (done-date "2007/1/30"))
((number 95)
 (status final)
 (title "Sorting and Merging")
 (authors "Aubrey Jaffer")
 (see-also)
 (keywords "algorithm")
 (draft-date "2006/10/17")
 (done-date "2007/1/29"))
((number 96)
 (status final)
 (title "SLIB Prerequisites")
 (authors "Aubrey Jaffer")
 (see-also)
 (keywords "features")
 (draft-date "2007/11/19")
 (done-date "2008/7/7"))
((number 97)
 (status final)
 (title "SRFI Libraries")
 (authors "David Van Horn")
 (see-also)
 (keywords "modules")
 (draft-date "2008/03/25")
 (done-date "2008/12/22"))
((number 98)
 (status final)
 (title "An interface to access environment variables")
 (authors "Taro Minowa (Higepon)")
 (see-also)
 (keywords "operating-system")
 (draft-date "2008/07/06")
 (done-date "2008/9/19"))
((number 99)
 (status final)
 (title "ERR5RS Records")
 (authors "William D Clinger")
 (see-also)
 (keywords "data-structure")
 (draft-date "2008/07/22")
 (done-date "2009/10/7"))
((number 100)
 (status final)
 (title "define-lambda-object")
 (authors "Joo ChurlSoo")
 (see-also)
 (keywords "data-structure")
 (draft-date "2009/09/09")
 (done-date "2010/6/21"))
((number 101)
 (status final)
 (title "Purely Functional Random-Access Pairs and Lists")
 (authors "David Van Horn")
 (see-also)
 (keywords "data-structure")
 (draft-date "2009/09/16")
 (done-date "2013/2/24"))
((number 102)
 (status withdrawn)
 (title "Procedure Arity Inspection")
 (authors "David Van Horn")
 (see-also)
 (keywords "introspection")
 (draft-date "2009/09/21")
 (done-date "2013/02/24"))
((number 103)
 (status withdrawn)
 (title "Library Files")
 (authors "Derick Eddington")
 (see-also)
 (keywords "operating-system")
 (draft-date "2009/09/22")
 (done-date "2013/05/08"))
((number 104)
 (status withdrawn)
 (title "Library Files Utilities")
 (authors "Derick Eddington")
 (see-also)
 (keywords "operating-system")
 (draft-date "2009/09/22")
 (done-date "2010/05/23"))
((number 105)
 (status final)
 (title "Curly-infix-expressions")
 (authors "David A. Wheeler, Alan Manuel K. Gloria")
 (see-also)
 (keywords "reader-syntax")
 (draft-date "2012/08/22")
 (done-date "2012/11/6"))
((number 106)
 (status final)
 (title "Basic socket interface")
 (authors "Takashi Kato")
 (see-also)
 (keywords "i/o")
 (draft-date "2012/10/06")
 (done-date "2013/8/20"))
((number 107)
 (status final)
 (title "XML reader syntax")
 (authors "Per Bothner")
 (see-also)
 (keywords "reader-syntax")
 (draft-date "2012/11/10")
 (done-date "2013/12/22"))
((number 108)
 (status final)
 (title "Named quasi-literal constructors")
 (authors "Per Bothner")
 (see-also)
 (keywords "reader-syntax")
 (draft-date "2012/11/10")
 (done-date "2013/6/21"))
((number 109)
 (status final)
 (title "Extended string quasi-literals")
 (authors "Per Bothner")
 (see-also)
 (keywords "reader-syntax")
 (draft-date "2012/11/10")
 (done-date "2013/6/21"))
((number 110)
 (status final)
 (title "Sweet-expressions (t-expressions)")
 (authors "David A. Wheeler, Alan Manuel K. Gloria")
 (see-also)
 (keywords "reader-syntax")
 (draft-date "2013/03/06")
 (done-date "2013/9/9"))
((number 111)
 (status final)
 (title "Boxes")
 (authors "John Cowan")
 (see-also)
 (keywords "data-structure")
 (draft-date "2013/04/25")
 (done-date "2013/7/3"))
((number 112)
 (status final)
 (title "Environment Inquiry")
 (authors "John Cowan")
 (see-also)
 (keywords "operating-system")
 (draft-date "2013/05/05")
 (done-date "2013/9/12"))
((number 113)
 (status final)
 (title "Sets and bags")
 (authors "John Cowan")
 (see-also)
 (keywords "data-structure")
 (draft-date "2013/06/01")
 (done-date "2014/11/28"))
((number 114)
 (status withdrawn)
 (title "Comparators")
 (authors "John Cowan")
 (see-also 128)
 (keywords "comparison" "superseded")
 (draft-date "2013/06/15")
 (done-date "2017/8/10"))
((number 115)
 (status final)
 (title "Scheme Regular Expressions")
 (authors "Alex Shinn")
 (see-also)
 (keywords "data-structure")
 (draft-date "2013/10/12")
 (done-date "2014/7/14"))
((number 116)
 (status final)
 (title "Immutable List Library")
 (authors "John Cowan")
 (see-also)
 (keywords "data-structure")
 (draft-date "2014/09/08")
 (done-date "2014/11/28"))
((number 117)
 (status final)
 (title "Mutable Queues")
 (authors "John Cowan")
 (see-also)
 (keywords "data-structure")
 (draft-date "2014/12/02")
 (done-date "2015/8/25"))
((number 118)
 (status final)
 (title "Simple adjustable-size strings")
 (authors "Per Bothner")
 (see-also 135 140)
 (keywords "data-structure")
 (draft-date "2014/12/20")
 (done-date "2015/7/7"))
((number 119)
 (status final)
 (title "wisp: simpler indentation-sensitive scheme")
 (authors "Arne Babenhauserheide")
 (see-also)
 (keywords "reader-syntax")
 (draft-date "2015/02/03")
 (done-date "2015/6/23"))
((number 120)
 (status final)
 (title "Timer APIs")
 (authors "Takashi Kato")
 (see-also)
 (keywords "miscellaneous")
 (draft-date "2015/2/4")
 (done-date "2015/8/6"))
((number 121)
 (status withdrawn)
 (title "Generators")
 (authors "Shiro Kawai, John Cowan, Thomas Gilray")
 (see-also 158)
 (keywords "data-structure" "superseded")
 (draft-date "2015/01/27")
 (done-date "2019/7/18"))
((number 122)
 (status final)
 (title "Nonempty Intervals and Generalized Arrays")
 (authors "Bradley J. Lucier")
 (see-also)
 (keywords "data-structure")
 (draft-date "2015/7/27")
 (done-date "2016/12/24"))
((number 123)
 (status final)
 (title "Generic accessor and modifier operators")
 (authors "Taylan Ulrich Bayırlı/Kammer")
 (see-also)
 (keywords "miscellaneous")
 (draft-date "2015/8/15")
 (done-date "2015/10/14"))
((number 124)
 (status final)
 (title "Ephemerons")
 (authors "John Cowan")
 (see-also)
 (keywords "data-structure")
 (draft-date "2015/9/6")
 (done-date "2015/11/6"))
((number 125)
 (status final)
 (title "Intermediate hash tables")
 (authors "John Cowan, Will Clinger")
 (see-also 69 126)
 (keywords "data-structure")
 (draft-date "2015/9/7")
 (done-date "2015/5/28"))
((number 126)
 (status final)
 (title "R6RS-based hashtables")
 (authors "Taylan Ulrich Bayırlı/Kammer")
 (see-also 69 125)
 (keywords "data-structure")
 (draft-date "2015/9/8")
 (done-date "2016/2/1"))
((number 127)
 (status final)
 (title "Lazy Sequences")
 (authors "John Cowan")
 (see-also)
 (keywords "data-structure")
 (draft-date "2015/10/20")
 (done-date "2016/1/18"))
((number 128)
 (status final)
 (title "Comparators (reduced)")
 (authors "John Cowan")
 (see-also 114)
 (keywords "comparison")
 (draft-date "2015/10/26")
 (done-date "2016/2/14"))
((number 129)
 (status final)
 (title "Titlecase procedures")
 (authors "John Cowan")
 (see-also)
 (keywords "internationalization")
 (draft-date "2015/11/30")
 (done-date "2016/3/8"))
((number 130)
 (status final)
 (title "Cursor-based string library")
 (authors "John Cowan")
 (see-also 13)
 (keywords "data-structure")
 (draft-date "2015/12/3")
 (done-date "2016/5/28"))
((number 131)
 (status final)
 (title "ERR5RS Record Syntax (reduced)")
 (authors "John Cowan, Will Clinger")
 (see-also 150)
 (keywords "data-structure")
 (draft-date "2015/12/7")
 (done-date "2016/2/13"))
((number 132)
 (status final)
 (title "Sort Libraries")
 (authors "John Cowan (based on SRFI 32 by Olin Shivers)")
 (see-also)
 (keywords "algorithm")
 (draft-date "2015/12/9")
 (done-date "2016/4/20"))
((number 133)
 (status final)
 (title "Vector Library (R7RS-compatible)")
 (authors "John Cowan (based on SRFI 43 by Taylor Campbell)")
 (see-also 43 160)
 (keywords "data-structure")
 (draft-date "2015/12/16")
 (done-date "2016/3/20"))
((number 134)
 (status final)
 (title "Immutable Deques")
 (authors "Kevin Wortman, John Cowan")
 (see-also)
 (keywords "data-structure")
 (draft-date "2015/12/16")
 (done-date "2016/7/1"))
((number 135)
 (status final)
 (title "Immutable Texts")
 (authors "William D Clinger")
 (see-also 118 130 140 152)
 (keywords "data-structure")
 (draft-date "2016/6/6")
 (done-date "2016/9/6"))
((number 136)
 (status final)
 (title "Extensible record types")
 (authors "Marc Nieper-Wißkirchen")
 (see-also)
 (keywords "data-structure")
 (draft-date "2016/6/23")
 (done-date "2016/12/25"))
((number 137)
 (status final)
 (title "Minimal Unique Types")
 (authors "John Cowan, Marc Nieper-Wißkirchen")
 (see-also)
 (keywords "data-structure")
 (draft-date "2016/6/27")
 (done-date "2016/10/4"))
((number 138)
 (status final)
 (title "Compiling Scheme programs to executables")
 (authors "Marc Nieper-Wißkirchen")
 (see-also)
 (keywords "operating-system")
 (draft-date "2016/7/6")
 (done-date "2016/9/28"))
((number 139)
 (status final)
 (title "Syntax parameters")
 (authors "Marc Nieper-Wißkirchen")
 (see-also)
 (keywords "binding" "parameters")
 (draft-date "2016/7/7")
 (done-date "2016/10/2"))
((number 140)
 (status final)
 (title "Immutable Strings")
 (authors "Per Bothner")
 (see-also 118 135)
 (keywords "data-structure")
 (draft-date "2016/7/11")
 (done-date "2017/5/24"))
((number 141)
 (status final)
 (title "Integer division")
 (authors "Taylor Campbell, John Cowan")
 (see-also)
 (keywords "arithmetic")
 (draft-date "2016/8/29")
 (done-date "2016/12/14"))
((number 142)
 (status withdrawn)
 (title "Bitwise Operations")
 (authors "John Cowan")
 (see-also 151)
 (keywords "data-structure" "superseded")
 (draft-date "2016/9/20")
 (done-date "2017/8/10"))
((number 143)
 (status final)
 (title "Fixnums")
 (authors "John Cowan")
 (see-also)
 (keywords "arithmetic")
 (draft-date "2016/9/20")
 (done-date "2017/5/27"))
((number 144)
 (status final)
 (title "Flonums")
 (authors "John Cowan, Will Clinger")
 (see-also)
 (keywords "arithmetic")
 (draft-date "2016/9/20")
 (done-date "2017/7/17"))
((number 145)
 (status final)
 (title "Assumptions")
 (authors "Marc Nieper-Wißkirchen")
 (see-also)
 (keywords "optimization")
 (draft-date "2016/12/18")
 (done-date "2017/3/31"))
((number 146)
 (status final)
 (title "Mappings")
 (authors "Arthur A. Gleckler, Marc Nieper-Wißkirchen")
 (see-also)
 (keywords "data-structure")
 (draft-date "2016/12/18")
 (done-date "2018/5/24"))
((number 147)
 (status final)
 (title "Custom macro transformers")
 (authors "Marc Nieper-Wißkirchen")
 (see-also)
 (keywords "syntax")
 (draft-date "2016/12/24")
 (done-date "2017/3/7"))
((number 148)
 (status final)
 (title "Eager syntax-rules")
 (authors "Marc Nieper-Wißkirchen")
 (see-also)
 (keywords "syntax")
 (draft-date "2016/12/31")
 (done-date "2017/8/8"))
((number 149)
 (status final)
 (title "Basic Syntax-rules Template Extensions")
 (authors "Marc Nieper-Wißkirchen")
 (see-also)
 (keywords "syntax")
 (draft-date "2017/1/1")
 (done-date "2017/7/8"))
((number 150)
 (status final)
 (title "Hygienic ERR5RS Record Syntax (reduced)")
 (authors "Marc Nieper-Wißkirchen")
 (see-also 9 99 131)
 (keywords "data-structure")
 (draft-date "2017/1/2")
 (done-date "2018/1/16"))
((number 151)
 (status final)
 (title "Bitwise Operations")
 (authors "John Cowan")
 (see-also 142)
 (keywords "data-structure")
 (draft-date "2017/5/3")
 (done-date "2017/7/10"))
((number 152)
 (status final)
 (title "String Library (reduced)")
 (authors "John Cowan")
 (see-also 130 135)
 (keywords "data-structure")
 (draft-date "2017/6/3")
 (done-date "2017/10/4"))
((number 153)
 (status withdrawn)
 (title "Ordered Sets")
 (authors "John Cowan")
 (see-also)
 (keywords "data-structure")
 (draft-date "2017/6/28")
 (done-date "2018/7/8"))
((number 154)
 (status final)
 (title "First-class dynamic extents")
 (authors "Marc Nieper-Wißkirchen")
 (see-also 157)
 (keywords "miscellaneous")
 (draft-date "2017/7/3")
 (done-date "2018/9/15"))
((number 155)
 (status final)
 (title "Promises")
 (authors "Marc Nieper-Wißkirchen")
 (see-also 45)
 (keywords "data-structure" "lazy-evaluation")
 (draft-date "2017/7/4")
 (done-date "2018/9/15"))
((number 156)
 (status final)
 (title "Syntactic combiners for binary predicates")
 (authors "Panicz Maciej Godek")
 (see-also 26)
 (keywords "syntax")
 (draft-date "2017/7/10")
 (done-date "2017/12/18"))
((number 157)
 (status final)
 (title "Continuation marks")
 (authors "Marc Nieper-Wißkirchen")
 (see-also)
 (keywords "continuations")
 (draft-date "2017/7/17")
 (done-date "2018/1/29"))
((number 158)
 (status final)
 (title "Generators and Accumulators")
 (authors "Shiro Kawai, John Cowan, Thomas Gilray")
 (see-also 121)
 (keywords "data-structure")
 (draft-date "2017/8/12")
 (done-date "2017/10/27"))
((number 159)
 (status final)
 (title "Combinator Formatting")
 (authors "Alex Shinn")
 (see-also 28 48)
 (keywords "i/o")
 (draft-date "2017/8/21")
 (done-date "2018/1/17"))
((number 160)
 (status draft)
 (title "Homogeneous numeric vector libraries")
 (authors "John Cowan (based on SRFI 4 by Marc Feeley)")
 (see-also 4 133 152)
 (optionally-depends-on 121)
 (keywords "data-structure")
 (draft-date "2018/5/21"))
((number 161)
 (status final)
 (title "Unifiable Boxes")
 (authors "Marc Nieper-Wißkirchen")
 (see-also 111)
 (sample-implementation-languages r7rs-small)
 (keywords "data-structure")
 (draft-date "2018/9/6")
 (done-date "2019/2/8"))
((number 162)
 (status draft)
 (title "Comparators sublibrary")
 (authors "John Cowan")
 (see-also 128)
 (alternative-to 114)
 (optionally-depends-on 128)
 (sample-implementation-languages r7rs-small chibi)
 (keywords "comparison")
 (draft-date "2018/10/15"))
((number 163)
 (status final)
 (title "Enhanced array literals")
 (authors "Per Bothner")
 (see-also 4 25 48 58 122 58 160 164)
 (sample-implementation-languages kawa)
 (sample-implementation-depends-on 109 164)
 (keywords "reader-syntax")
 (draft-date "2018/11/1")
 (done-date "2019/1/18"))
((number 164)
 (status draft)
 (title "Enhanced multi-dimensional Arrays")
 (authors "Per Bothner")
 (see-also 4 25 122 163)
 (conflicts-with 47)
 (optionally-depends-on 17)
 (keywords "data-structure")
 (draft-date "2018/11/2"))
((number 165)
 (status draft)
 (title "The Environment Monad")
 (authors "Marc Nieper-Wißkirchen")
 (see-also 159 166)
 (sample-implementation-languages r7rs-small)
 (sample-implementation-depends-on 1 64 111 125 128 146)
 (keywords "miscellaneous")
 (draft-date "2019/2/13"))
((number 166)
 (status draft)
 (title "Monadic Formatting")
 (authors "Alex Shinn")
 (see-also 13 159)
 (optionally-depends-on 165)
 (sample-implementation-depends-on 1 69 117 130)
 (keywords "i/o")
 (draft-date "2019/3/27"))
((number 167)
 (status draft)
 (title "Ordered Key Value Store")
 (authors "Amirouche Boubekki")
 (see-also 168)
 (depends-on 158)
 (sample-implementation-depends-on 146)
 (keywords "i/o")
 (draft-date "2019/4/18"))
((number 168)
 (status draft)
 (title "Generic Tuple Store Database")
 (authors "Amirouche Boubekki")
 (see-also 167)
 (depends-on 9 128 146 158 167)
 (keywords "i/o")
 (draft-date "2019/4/18"))
((number 169)
 (status final)
 (title "Underscores in Numbers")
 (authors "Lassi Kortela")
 (see-also)
 (keywords "syntax")
 (done-date "2019/7/26")
 (draft-date "2019/4/18"))
((number 170)
 (status draft)
 (title "POSIX API")
 (authors "Olin Shivers (original author), John Cowan (editor and shepherd)")
 (see-also)
 (keywords "operating-system")
 (draft-date "2019/5/4"))
((number 171)
 (status draft)
 (title "Transducers")
 (authors "Linus Björnstam")
 (see-also)
 (depends-on 9)
 (optionally-depends-on 9 43)
 (keywords "data-structure")
 (draft-date "2019/6/20"))
((number 172)
 (status draft)
 (title "Two Safer Subsets of R7RS")
 (authors "John Cowan")
 (see-also)
 (keywords "miscellaneous")
 (draft-date "2019/7/2"))
